title: "Velkris — Red Team & Adversary Simulation"
description: "Adversary simulation, red team labs, and detection validation."
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
markdown: kramdown
url: "https://warpedatom.github.io"
baseurl: "/Velkris-Red-Team-Portfolio"
author:
  name: "Velkris (warpedatom)"
  bio: "Offensive security, red teaming, and adversary simulation research"
  avatar: "/assets/Dread-Host-Banner.png"
include:
  - _pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
